### ISSUE TITLE
Use nanoflann for tree search

### ISSUE THREAD

**Issue by prashjha** [nonlocalmodels/NLMech#135]

**Comment by diehlpk** [comment]
What is the difference between nanoflann and flann?

**Comment by prashjha** [comment]
Nanoflann is pretty light and header only...so it saves us from having to compile PCL which is a big headache. Nanoflann seem to be faster than pcl in many tests I have done.

**Comment by prashjha** [comment]
library is hosted here: https://github.com/jlblancoc/nanoflann

**Comment by diehlpk** [comment]
Ok, sure go ahead.
