### ISSUE TITLE
2D tests failed due to the uninitialized input vector

### ISSUE THREAD

**Issue by qingbyin** [nonlocalmodels/NLMech#142]
The 2D test in `example/qsModel/2D`  failed with segmentation faults.
After a quick debug, I found the program terminated at  this code line:
https://github.com/nonlocalmodels/NLMech/blob/f68fe3f241f83577d7a5e6aed1d87d952d393d2d/src/loading/uLoading.cpp#L207

`bc.d_spatialFnParams` is an uninitialized vector and core dump arised when accessing it.

This issue can be reproduced using the docker:

```
docker run -it docker.io/diehlpk/nlmech /bin/bash
cd NLMech/examples/qsModel/2D
/app/NLMech/build/bin/mesh -i input_mesh.yaml -d 2
/app/NLMech/build/bin/NLMech -i input.yaml --hpx:threads=2
```

**Comment by diehlpk** [comment]
@qingbyin Thanks for checking out the code, the issues is in the input file which was not updated to the latest version of the code.

**Comment by diehlpk** [comment]
@qingbyin The above pull request will fix your issue. It should be fixed in the Docker image tomorrow.
